/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package praxis;

public class App {
    

    public static void main(String[] args) {
        mahasiswa ohmahasiswa = new mahasiswa("","","","","","");
        ohmahasiswa.nama= "MUHAMMAD SULTONI";
        ohmahasiswa.alamat= "TEMUKEREP";
        ohmahasiswa.NoHanphone="085600273332";
        ohmahasiswa.Nim="333232323242";
        ohmahasiswa.Prodi="informatika";
        ohmahasiswa.Semester="5";
        System.out.println(ohmahasiswa.nama);
        System.out.println(ohmahasiswa.alamat);
        System.out.println(ohmahasiswa.NoHanphone);
        System.out.println(ohmahasiswa.Nim);
        System.out.println(ohmahasiswa.Prodi);
        System.out.println(ohmahasiswa.Semester);
        Dosen ohDosen = new Dosen("","","","","","");
        ohDosen.Nip= "2101212102102120";
        ohDosen.gelar= "Sarjana Magister";
        ohDosen.jabatan= "Dekan Fakultas";
        ohDosen.nama="Patih Gajah Mada";
        ohDosen.alamat="Yogyakarta";
        ohDosen.NoHanphone="0898298748744";
        System.out.println(ohDosen.Nip);
        System.out.println(ohDosen.gelar);
        System.out.println(ohDosen.jabatan);
        System.out.println(ohDosen.nama);
        System.out.println(ohDosen.alamat);
        System.out.println(ohDosen.NoHanphone);
    }

}
